---
- name: Prepare all Kubernetes nodes
  hosts: kube_cluster
  become: true

  roles:
    - common
    - containerd
    - kubernetes


- name: Initialize Kubernetes control plane
  hosts: kube_control_plane
  become: true

  roles:
    - control_plane
    - cilium
