---
- name: Configuring all Kubernetes nodes
  hosts: kube_cluster
  become: true
  roles:
    - common                                # Role to enable ip forwarding on all cluster (including control node)
    - containerd                            # Installing CRI on all cluster nodes (including control node)
    - kubernetes                            # Installing kubeadm and kubelet on all cluster nodes (including control node)

- name: Initialize Kubernetes control plane
  hosts: kube_control_plane
  become: true
  roles:
    - control_plane
    - cilium

- name: Initialize Kubernetes worker nodes
  hosts: kube_workers
  become: true
  roles:
    - worker_join

- name: Initializing kubectl on Hosts machine
  hosts: kube_hosts
  become: true
  roles:
    - kubectl_setup

# - name: Configuring Hosts machine to access k8s cluster
#   hosts: kube_hosts
#   become: true
#   roles:
#     - k8s_access
    
