---
- name: Check whether worker is already part of Kubernetes cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_config

- name: Join worker node to Kubernetes cluster
  ansible.builtin.command:
    cmd: "{{ hostvars[groups['kube_control_plane'][0]].kubeadm_join_command.stdout }}"
  when: not kubelet_config.stat  
