[local]
localhost ansible_connection=local

[engineer]
emp1 ansible_hosts=

[kube_hosts:children]
local
engineer

[kube_control_plane]
control-plane ansible_host=10.0.10.100

[kube_workers]
worker1 ansible_host=10.0.10.101
worker2 ansible_host=10.0.10.102

[kube_cluster:children]
kube_control_plane
kube_workers

[kube_cluster:vars]
ansible_user=ubuntu
ansible_become=true
ansible_ssh_private_key_file=~/.ssh/k8s-cluster.pem

[kube_hosts:vars]
ansible_user=ubuntu
ansible_become=true
ansible_ssh_private_key_file=~/.ssh/hosts.pem
