[kube_hosts]

[kube_control_plane]
control-plane ansible_host=10.0.10.100

[kube_workers]
worker1 ansible_host=10.0.10.101
worker2 ansible_host=10.0.10.102

[kube_cluster:children]
kube_control_plane
kube_workers

[kube_cluster:vars]
ansible_user=ubuntu
ansible_become=true


